name: "mypy check"
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:

  static-type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - run: pip install mypy
    - name: Run mypy check on all files
      run: mypy --strict .
